### ISSUE TITLE
Extension methods are not listed in dependencies

### ISSUE THREAD

**Issue by Rubbiroid** [TNG/ArchUnitNET#6]
If a class uses an extension method, this extension method is not listed in the dependencies of this class.

**Comment by fgather** [comment]
Released in 0.2.1

**Comment by Rubbiroid** [comment]
still don't work...

Example code to reproduce:
`
using Castle.Core.Internal;
public class SomeClass
{
  public bool MethodWithDependency()
  {
    var list = new List<string>();
    return list.IsNullOrEmpty();
  }
}
`

Test:
`
  Classes()
    .Should().NotDependOnAny("Castle.Core.Internal")
    .Check(Architecture);
`

**Comment by fgather** [comment]
@Rubbiroid , can you retest? Is it fixed now?

**Comment by Rubbiroid** [comment]
nope. Still doesn't work. Maybe it needs generic support as particular extensions uses generics

**Comment by fgather** [comment]
I think I added a test case for this in the new generics code on staging. Should be fixed soon, but we don't want to rush things there.

**Comment by fgather** [comment]
This should be fixed with the current release. Can you test it?

**Comment by fgather** [comment]
I'll close this, since it should be fixed.
